### ISSUE TITLE
Parse magic failed

### ISSUE THREAD

**Issue by Feodoros** [takuya-takeuchi/UltraFaceDotNet#9]
Hello, I try to use your model. I've installed nuget packages and loaded these bin and param files (RFB-320.bin, RFB-320.param). 
But it failed with this error: System.AccessViolationException at the string `var faceInfos = ultraFace.Detect(inMat).ToArray();`.

And it writes in the console this message 
![изображение](https://user-images.githubusercontent.com/23313519/90523035-194b2600-e175-11ea-9111-e17b69288ce3.png)

My code looks like code from your demo example.
![изображение](https://user-images.githubusercontent.com/23313519/90522951-00427500-e175-11ea-92e1-67a504ff8f74.png)

Any ideas to fix this?

**Comment by Feodoros** [comment]
![изображение](https://user-images.githubusercontent.com/23313519/90523601-bf972b80-e175-11ea-88f6-77b8c0a99482.png)

**Comment by takuya-takeuchi** [comment]
@Feodoros 
I guess your RFB320.param is corrupted.
I deployed the correct RFB-320.bin and corrupted RFB-320.param (param is renamed RFB-320.bin).
This is result of running program.

````powershell
dotnet run -c Release -- RFB-320.bin RFB-320.param test.jpg
parse magic failed
network graph not ready
Processing test.jpg
find_blob_index_by_name input.1 failed
find_blob_index_by_name 537 failed
find_blob_index_by_name 538 failed
find_blob_index_by_name 539 failed
find_blob_index_by_name 540 failed
heatMap is nullptr,please check!
````

At least, `parse magic failed` means that parameter file has something wrong.
https://github.com/Tencent/ncnn/blob/e841ae73c6f1282c365be84f226bfff56c37c367/src/net.cpp#L517

**Comment by Feodoros** [comment]
Hello, thank you for your fast reply. Yes, it's really works! One more question: Does this nuget package work on Windows 7 x64?

**Comment by Feodoros** [comment]
And I got memory leak too. I cloned your last develop branch, but still have this memory leak, when I work with loop of images. 
How I can fix this?
https://github.com/takuya-takeuchi/UltraFaceDotNet/issues/3

**Comment by Feodoros** [comment]
OK. I fixed this with this simple Dispose of all objects. Sorry for my concern :)
![изображение](https://user-images.githubusercontent.com/23313519/90633340-8a9adf80-e22e-11ea-9e6a-9723c4709d00.png)

**Comment by takuya-takeuchi** [comment]
@Feodoros 

> Hello, thank you for your fast reply. Yes, it's really works! One more question: Does NcnnDotNet nuget package work on Windows 7 x64?

I think so. But I have not ever tried.

> OK. I fixed this with this simple Dispose of all objects. Sorry for my concern :)

No problem :)
